baseurl = "http://moontowercider.com/"
languageCode = "en-us"
title = "Moontower Cider | Crafted in East Austin Texas"

enableRobotsTXT = true

[params]
    subtitle = "Wat"
    author = "Thomas Ruble"
