baseurl = "http://moontowercider.com/"
languageCode = "en-us"
title = "Moontower Cider | Crafted in East Austin Texas"

enableRobotsTXT = true

[params]
    author = "Thomas Ruble"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"